set.seed(0102)
options(htmlwidgets.TOJSON_ARGS = list(pretty = TRUE), htmltools.dir.version = FALSE)
Sys.setenv(R_KNITR_OPTIONS = 'knitr.chunk.tidy=FALSE')
library(DT)
rmarkdown::render(commandArgs(TRUE))
