#' Helper functions for using DT in Shiny
#'
#' These two functions are like most \code{fooOutput()} and \code{renderFoo()}
#' functions in the \pkg{shiny} package. The former is used to create a
#' container for table, and the latter is used in the server logic to render the
#' table.
#' @inheritParams shiny::dataTableOutput
#' @param width the width of the table container
#' @param height the height of the table container
#' @export
#' @examples # !formatR
#' if (interactive()) {
#'   library(shiny)
#'   shinyApp(
#'     ui = fluidPage(fluidRow(column(12, DT::dataTableOutput('tbl')))),
#'     server = function(input, output) {
#'       output$tbl = DT::renderDataTable(DT::datatable(iris))
#'     }
#'   )
#' }
dataTableOutput = function(outputId, width = '100%', height = 'auto') {
  htmlwidgets::shinyWidgetOutput(
    outputId, 'datatables', width, height, package = 'DT'
  )
}

#' @export
#' @rdname dataTableOutput
#' @inheritParams shiny::renderDataTable
#' @param expr an expression to create a table widget
#' @param ... currently ignored, with a warning message
renderDataTable = function(expr, env = parent.frame(), quoted = FALSE, ...) {
  if (length(list(...))) warning(
    "Arguments in addition to 'expr', 'env', and 'quoted' are ignored. ",
    "If you came from shiny::renderDataTable(), you may want to pass ",
    "these arguments to DT::datatable() instead."
  )
  if (!quoted) expr = substitute(expr)
  htmlwidgets::shinyRenderWidget(expr, dataTableOutput, env, quoted = TRUE)
}

#' Append a column of checkboxes to the data for selecting rows
#'
#' Append a column of checkboxes with the CSS class \samp{DT checkboxRows} to
#' the data. The checkboxes can be used for selecting rows in Shiny. Each
#' checkbox has a data field \samp{data-row} that contains the index of the
#' current row. The HTML code for checkboxes are generated by
#' \code{checkboxRows()}.
#'
#' For a table output with id \code{foo} in Shiny, the indices of the selected
#' rows are stored in \code{input$foo_selected}.
#' @param data the data to be displayed as the table
#' @param after add the checkboxes after the last column (\code{TRUE}) or before
#'   the first column (\code{FALSE}) of the table
#' @param checked which checkboxes are checked initially (a logical or numeric
#'   vector)
#' @references See \url{http://rstudio.github.io/DT/shiny.html} for examples.
#' @examples library(DT)
#' datatable(appendCheckboxes(iris), escape = -7)
#' @export
appendCheckboxes = function(data, after = TRUE, checked = FALSE) {
  check = checkboxRows(data, checked)
  if (after) cbind(data, ' ' = check) else cbind(' ' = check, data)
}

#' @rdname appendCheckboxes
#' @export
checkboxRows = function(data, checked = FALSE) {
  n = nrow(data)
  s = character(n)
  # we could have generated the checkboxes from tags$input() but it is much
  # slower than the simple sprintf() here; on the other hand, there is no need
  # to escape numbers seq_len(n) since they do not contain special HTML chars
  s[checked] = 'checked '
  sprintf(
    '<input data-row="%s" type="checkbox" class="DT checkboxRows" %s/>',
    seq_len(n), s
  )
}
